"""Initial schema: 7 tables, 2 enums, 12 indexes (schema.md rev 4, compact DDL).

Delivers schema.md (full), ADR-005 (SQLAlchemy 2.x + Alembic + psycopg 3),
ADR-006 (managed PostgreSQL, additive-only migrations), ADR-016 (complaint
number CHECK), ADR-022 (idempotent complaint creation via client_request_id).

Hand-written from the "Compact DDL sketch" in schema.md, NOT autogenerated —
`target_metadata` does not exist until T-004 (see migrations/env.py).

Append-only enforcement for `complaint_status_history`, `complaint_edit_history`
and `security_event` is application-level only as of this revision (see the
comment ahead of `upgrade()` below) — TD-B04.

Revision ID: 0001
Revises:
Create Date: 2026-09-10

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_COMPLAINT_STATUS_VALUES = ("new", "in_progress", "resolved", "rejected", "closed")
_SECURITY_EVENT_TYPE_VALUES = (
    "login_success",
    "login_failure",
    "account_created",
    "password_reset_issued",
    "throttle_lookup",
    "throttle_login",
    "throttle_detail",
    "throttle_write",
    "throttle_search",
    "account_unlocked",
)


def _complaint_status_enum(*, create_type: bool) -> postgresql.ENUM:
    return postgresql.ENUM(
        *_COMPLAINT_STATUS_VALUES, name="complaint_status", create_type=create_type
    )


def _security_event_type_enum(*, create_type: bool) -> postgresql.ENUM:
    return postgresql.ENUM(
        *_SECURITY_EVENT_TYPE_VALUES, name="security_event_type", create_type=create_type
    )


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "clerk_account",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("username", sa.String(length=30), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("is_admin_clerk", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column(
            "must_change_password", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
        sa.Column("password_is_otp", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column(
            "password_set_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.UniqueConstraint("username", name="uq_clerk_account_username"),
        sa.CheckConstraint(
            r"username ~ '^[A-Za-z0-9_]{3,30}$'", name="ck_clerk_account_username_format"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["clerk_account.id"],
            name="fk_clerk_account_created_by_clerk_account",
            ondelete="SET NULL",
        ),
    )

    op.create_table(
        "session",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("csrf_token", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("token_hash", name="uq_session_token_hash"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["clerk_account.id"],
            name="fk_session_user_id_clerk_account",
            ondelete="CASCADE",
        ),
    )
    op.create_index("ix_session_user_id", "session", ["user_id"])

    _complaint_status_enum(create_type=True).create(op.get_bind(), checkfirst=False)
    _security_event_type_enum(create_type=True).create(op.get_bind(), checkfirst=False)

    op.create_table(
        "complaint",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("complaint_number", sa.CHAR(length=9), nullable=False),
        sa.Column("client_request_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("citizen_name", sa.String(length=100), nullable=False),
        sa.Column("citizen_phone", sa.String(length=16), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column(
            "status",
            _complaint_status_enum(create_type=False),
            nullable=False,
            server_default="new",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.UniqueConstraint("complaint_number", name="uq_complaint_number"),
        sa.UniqueConstraint("client_request_id", name="uq_complaint_client_request_id"),
        sa.CheckConstraint(
            "complaint_number ~ '^[0-9A-HJKMNP-TV-Z]{9}$'",
            name="ck_complaint_number_format",
        ),
        sa.CheckConstraint(
            "length(trim(citizen_name)) > 0", name="ck_complaint_citizen_name_not_blank"
        ),
        sa.CheckConstraint(
            r"citizen_phone ~ '^\+?[0-9]{7,15}$'", name="ck_complaint_citizen_phone_format"
        ),
        sa.CheckConstraint(
            "length(trim(description)) > 0", name="ck_complaint_description_not_blank"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["clerk_account.id"],
            name="fk_complaint_created_by_clerk_account",
            ondelete="RESTRICT",
        ),
    )
    op.create_index(
        "ix_complaint_status_created_id",
        "complaint",
        ["status", sa.text("created_at DESC"), sa.text("id DESC")],
    )
    op.create_index(
        "ix_complaint_created_id", "complaint", [sa.text("created_at DESC"), sa.text("id DESC")]
    )

    op.create_table(
        "complaint_status_history",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("complaint_id", sa.BigInteger(), nullable=False),
        sa.Column("previous_status", _complaint_status_enum(create_type=False), nullable=False),
        sa.Column("new_status", _complaint_status_enum(create_type=False), nullable=False),
        sa.Column("note", sa.String(length=2000), nullable=True),
        sa.Column("actor_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "new_status <> previous_status", name="ck_complaint_status_history_status_changed"
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaint.id"],
            name="fk_complaint_status_history_complaint_id_complaint",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["clerk_account.id"],
            name="fk_complaint_status_history_actor_id_clerk_account",
            ondelete="RESTRICT",
        ),
    )
    op.create_index(
        "ix_csh_complaint_created",
        "complaint_status_history",
        ["complaint_id", "created_at", "id"],
    )

    op.create_table(
        "complaint_edit_history",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("complaint_id", sa.BigInteger(), nullable=False),
        sa.Column("field_name", sa.String(length=20), nullable=False),
        sa.Column("previous_value", sa.String(length=2000), nullable=False),
        sa.Column("new_value", sa.String(length=2000), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "field_name IN ('citizen_name','citizen_phone','description')",
            name="ck_complaint_edit_history_field_name_allowed",
        ),
        sa.CheckConstraint(
            "new_value IS DISTINCT FROM previous_value",
            name="ck_complaint_edit_history_value_changed",
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaint.id"],
            name="fk_complaint_edit_history_complaint_id_complaint",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["clerk_account.id"],
            name="fk_complaint_edit_history_actor_id_clerk_account",
            ondelete="RESTRICT",
        ),
    )
    op.create_index(
        "ix_ceh_complaint_created", "complaint_edit_history", ["complaint_id", "created_at", "id"]
    )

    op.create_table(
        "rate_limit_counter",
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.PrimaryKeyConstraint("scope", "key", "window_start", name="pk_rate_limit_counter"),
    )
    op.create_index("ix_rate_limit_counter_window_start", "rate_limit_counter", ["window_start"])

    op.create_table(
        "security_event",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("event_type", _security_event_type_enum(create_type=False), nullable=False),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("target_user_id", sa.BigInteger(), nullable=True),
        sa.Column("actor_username_hash", sa.CHAR(length=16), nullable=True),
        sa.Column("derived_ip", sa.String(length=45), nullable=True),
        sa.Column("reason_code", sa.String(length=40), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["clerk_account.id"],
            name="fk_security_event_actor_user_id_clerk_account",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["clerk_account.id"],
            name="fk_security_event_target_user_id_clerk_account",
            ondelete="SET NULL",
        ),
    )
    op.create_index("ix_security_event_created", "security_event", ["created_at"])

    # Append-only enforcement for complaint_status_history, complaint_edit_history
    # and security_event is the application-level `before_execute` guard
    # (app/db/guard.py, T-004) only, as of this revision. A DB-level
    # `REVOKE UPDATE, DELETE ... FROM <app_role>` (schema.md "Audit /
    # append-only enforcement", belt-and-braces layer) needs a second,
    # non-owning application role to have any effect — a table owner's
    # implicit privileges are unaffected by REVOKE — and no such role is
    # provisioned yet (local dev and CI both use a single role). That DB-level
    # hardening ships as its own dedicated later migration once the platform
    # names the second role, tracked as TD-B04.


def downgrade() -> None:
    """Downgrade schema.

    Mechanically safe here only because revision 0001 is the *first* revision:
    "downgrade to base" means there was never any data to lose. Later
    revisions must not follow this pattern for an established table (coding-
    guidelines.md § Migrations / schema.md § Migration strategy — additive-
    only, no destructive rollback of live data).
    """
    op.drop_table("security_event")
    op.drop_table("rate_limit_counter")
    op.drop_table("complaint_edit_history")
    op.drop_table("complaint_status_history")
    op.drop_table("complaint")
    op.drop_table("session")
    op.drop_table("clerk_account")

    _security_event_type_enum(create_type=True).drop(op.get_bind(), checkfirst=False)
    _complaint_status_enum(create_type=True).drop(op.get_bind(), checkfirst=False)
