/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/complaints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Complaint */
        post: operations["create_complaint_api_complaints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Public Lookup */
        post: operations["public_lookup_api_lookup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Info */
        get: operations["get_session_info_api_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnonymousSessionResponse */
        AnonymousSessionResponse: {
            /**
             * Authenticated
             * @constant
             */
            authenticated: false;
            /** Csrf Token */
            csrf_token: string;
        };
        /** AuthenticatedSessionResponse */
        AuthenticatedSessionResponse: {
            /**
             * Authenticated
             * @constant
             */
            authenticated: true;
            /** Csrf Token */
            csrf_token: string;
            user: components["schemas"]["SessionUserDTO"];
        };
        /**
         * ComplaintDTO
         * @description The create response (api-contract.md §7) — exactly the fields the
         *     contract names, no more (no `history`; that is a separate route).
         */
        ComplaintDTO: {
            /** Id */
            id: number;
            /** Complaint Number */
            complaint_number: string;
            /** Status */
            status: string;
            /** Citizen Name */
            citizen_name: string;
            /** Citizen Phone */
            citizen_phone: string;
            /** Description */
            description: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Created By */
            created_by: string;
            /** Legal Next Statuses */
            legal_next_statuses: string[];
            /**
             * Edit Window Expires At
             * Format: date-time
             */
            edit_window_expires_at: string;
            /** Duplicate */
            duplicate: boolean;
        };
        /** CreateComplaintRequest */
        CreateComplaintRequest: {
            /**
             * Client Request Id
             * Format: uuid
             */
            client_request_id: string;
            /** Citizen Name */
            citizen_name: string;
            /** Citizen Phone */
            citizen_phone: string;
            /** Description */
            description: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthzResponse */
        HealthzResponse: {
            /** Status */
            status: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            user: components["schemas"]["UserDTO"];
            /** Csrf Token */
            csrf_token: string;
        };
        /** LogoutResponse */
        LogoutResponse: {
            /** Csrf Token */
            csrf_token: string;
        };
        /** LookupRequest */
        LookupRequest: {
            /** Complaint Number */
            complaint_number: string;
        };
        /**
         * LookupResponseDTO
         * @description The entire public DTO, exhaustive (api-contract.md §4).
         */
        LookupResponseDTO: {
            /** Complaint Number */
            complaint_number: string;
            /** Status */
            status: string;
            /** Public Update */
            public_update: string;
            /**
             * Date Logged
             * Format: date
             */
            date_logged: string;
        };
        /** SessionUserDTO */
        SessionUserDTO: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Is Admin Clerk */
            is_admin_clerk: boolean;
            /** Must Change Password */
            must_change_password: boolean;
        };
        /**
         * UserDTO
         * @description The `user` object embedded in the login response (api-contract.md
         *     §3) — exactly the four fields the contract names, no more.
         */
        UserDTO: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Is Admin Clerk */
            is_admin_clerk: boolean;
            /** Must Change Password */
            must_change_password: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
        };
    };
    login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    create_complaint_api_complaints_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateComplaintRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    public_lookup_api_lookup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LookupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookupResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_info_api_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnonymousSessionResponse"] | components["schemas"]["AuthenticatedSessionResponse"];
                };
            };
        };
    };
}
